/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AvatarLetter: typeof import('./src/components/AvatarLetter.vue')['default']
    CustomerList: typeof import('./src/components/CustomerList.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    QrcodeCapture: typeof import('./src/components/QrcodeCapture.vue')['default']
    QrcodeDropZone: typeof import('./src/components/QrcodeDropZone.vue')['default']
    QrcodeStream: typeof import('./src/components/QrcodeStream.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Username: typeof import('./src/components/Username.vue')['default']
  }
}
